name: 京喜财富岛

on:
    workflow_dispatch:
    schedule:
        - cron: "*/15 * * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jx_cfd

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install got download tough-cookie
            - name: "运行 【京喜财富岛】"
              run: |
                  node jx_cfd.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
